### ISSUE TITLE
Integrate pre-commit in the repo

### ISSUE THREAD

**Issue by umairwaheed** [prixite/prixite.github.io#31]
- [ ] Add .pre-commit-config.yaml in root of this repo.
- [ ] Add a pre-commit.yml under .github/workflows.

The contents of  pre-commit.yml can be something like this:

```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
```

Contents of .pre-commit-config.yaml can be similar to:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - 
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: ^tweet_listener/models/
        types: [javascript]

```
